### ISSUE TITLE
Feature request: external url

### ISSUE THREAD

**Issue by altumICT** [robwierzbowski/jekyll-image-tag#11]
First of all thanks for this wonderful plugin!
For my sites, I host my assets on another (sub)domain to avoid that the cookies of my site are sent in the request headers for those static assets.
But it seems impossible to use the image-tag for that setup, because it is not possible to give a url-prefix. The src of the image is currently always relative to the root of the website, but I need to prefix that part with "http://assets.mydomain.com/"

Can you please add such an option to _config.yml? If it is there, it will be used, if not, it behaves as implemented in the current version, so it will keep everything backwards compatible.

Thanks in advance.

**Comment by robwierzbowski** [comment]
Continued discussion in https://github.com/robwierzbowski/jekyll-image-tag/pull/13.
