### ISSUE TITLE
Using variables in image tag

### ISSUE THREAD

**Issue by bonniee** [robwierzbowski/jekyll-image-tag#17]
I'm having issues getting the image tag working when I'm using variables. The below addition to my index.html causes a jekyll crash.

The code:

```
{% image {{post.image}}  %} 
```

The error:

```
     Generating...   Liquid Exception: undefined method `[]' for nil:NilClass in index.html
```

Any clues on how to fix this? Thanks!

**Comment by pruzicka** [comment]
same issue here.

**Comment by fregante** [comment]
Check out issue #18

**Comment by robwierzbowski** [comment]
Seems like #18 is the fix. Closed.
