### ISSUE TITLE
 Liquid Exception: undefined method `[]' for nil:NilClass in index.html

### ISSUE THREAD

**Issue by pruzicka** [robwierzbowski/jekyll-image-tag#18]
in index.html - {% image vyuka.jpg alt="Vyuka" %}
in config.yml
image: 
 source: img
 output: generated
Any idea what is going on ?
Thanks

**Comment by pruzicka** [comment]
solved, there needs to be presets.

**Comment by robwierzbowski** [comment]
Awesome! Yeah, the error messages should be more descriptive.

Rob Wierzbowski
@robwierzbowski http://twitter.com/#!/robwierzbowski
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by phillipadsmith** [comment]
Sorry, just to confirm using {% image 600x300 image-name.jpg %} won't work as described in the docs?

**Comment by k-funk** [comment]
+1
If the variable is nil, or the string doesn't have a file extension on it, you'll also get this message. Super difficult to debug.
