### ISSUE TITLE
Option to not crop

### ISSUE THREAD

**Issue by garygreen** [robwierzbowski/jekyll-image-tag#24]
Taking a look at the output and code it seems it's currently not possible to specify in your config if you want the output to be cropped or not? It would be good to have an option to keep the aspect ratio and not crop to the desired width/height.

**Comment by tag730** [comment]
I take it you mean an option to provide WIDTHxHEIGHT as a bounding box? So that whichever dimension is not the constraining dimension will automatically be treated as AUTO?

Looks like currently if you provide both WIDTH & HEIGHT, you're mandating the output W & H, not a bounding box.

**Comment by garygreen** [comment]
Exactly
