### ISSUE TITLE
Installing ImageMagick, MiniMagick

### ISSUE THREAD

**Issue by gorkamolero** [robwierzbowski/jekyll-image-tag#6]
Hey there!

First, congratulations on your Jekyll generator. It's helped a lot and works wonderfully. I'm trying to implement Jekyll image tags but installing them is much harder than it seems.

I installed ImageMagick from a binary by CactusLab,
http://cactuslab.com/imagemagick/assets/ImageMagick-6.8.6-3.pkg.zip

To install MiniMagick they clearly state on their site to just add the following to the Gemfile of the project:
gem 'mini_magick'

Apart from this I installed the gems for each of them,
gem install imagemagick, gem install mini_magick

Supposedly this would be enough, but this is the error that grunt is spitting:

Running "jekyll:server" (jekyll) task
`bundle exec jekyll build --source app --destination .jekyll --config _config.yml` was initiated.

Jekyll output:
Configuration file: _config.yml
            Source: app
       Destination: .jekyll
      Generating... Warning: Command failed:   Liquid Exception: undefined method `[]' for nil:NilClass in default.html
error: undefined method`[]' for nil:NilClass. Use --trace to view backtrace
 Use --force to continue.

Aborted due to warnings.

**Comment by gorkamolero** [comment]
Update:

I copied your sample configuration file and it seems the error is somewhere else, this is the new error I get from grunt:

```
Jekyll output:
Configuration file: _config.yml
            Source: app
       Destination: .jekyll
      Generating... Warning: Command failed:   Liquid Exception: Command ("identify -quiet -ping /var/folders/Ao/Ao105viQGLGvl-oKIa0i6E+++TY/-Tmp-/mini_magick20130830-65579-1x76d93.jpg") failed: {:status_code=>nil, :output=>"dyld: Library not loaded: /opt/X11/lib/libfreetype.6.dylib\n Referenced from: /opt/ImageMagick/bin/identify\n Reason: image not found\n"} in default.html
error: Command ("identify -quiet -ping /var/folders/Ao/Ao105viQGLGvl-oKIa0i6E+++TY/-Tmp-/mini_magick20130830-65579-1x76d93.jpg") failed: {:status_code=>nil, :output=>"dyld: Library not loaded: /opt/X11/lib/libfreetype.6.dylib\n  Referenced from: /opt/ImageMagick/bin/identify\n  Reason: image not found\n"}. Use --trace to view backtrace
 Use --force to continue.

Aborted due to warnings. Use --force to continue.

    Aborted due to warnings.
whom5000359:gorkamolero-jekyll gorka$ 
```

**Comment by fregante** [comment]
I had that same error, it turns out that my `_config.yml` was in the wrong folder and it wasn't being read at all.

**Comment by robwierzbowski** [comment]
Profile pic / comment synergy: 
![image](https://cloud.githubusercontent.com/assets/925735/3071604/d9facd36-e2b9-11e3-9082-f2b1346dc40a.png).

Closing; feel free to open a newer issues with any remaining problems.
